name: deepsleep
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  provider: ^6.1.4
  intl: ^0.20.2
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_time_picker_spinner: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.35.5
  permission_handler: ^12.0.0+1


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Agrega esta sección de assets (importante)
  assets:
    - assets/deepsleep-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/deepsleep-icon.png" # Cambiado a PNG (recomendado)
  min_sdk_android: 21
  android_adaptive_icon_foreground: "assets/deepsleep-icon-foreground.png"
  android_adaptive_icon_background: "#2E3192" # Color de fondo (ajusta este valor)
  remove_alpha_ios: true